"""Remove username field from User model

Revision ID: 3ef6c9135998
Revises: 92b306eb1f25
Create Date: 2024-12-11 12:08:51.059459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef6c9135998'
down_revision = '92b306eb1f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=80), nullable=False, unique=True))
    # ### end Alembic commands ###
