"""Add password field to User model

Revision ID: 92b306eb1f25
Revises: d9d44e45a069
Create Date: 2024-12-11 11:59:26.102619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b306eb1f25'
down_revision = 'd9d44e45a069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=False))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')

    # ### end Alembic commands ###
